import { FideLedgerDatabase, syncOpponentsWithGames } from '../services/jsonbinService';
import { OpponentPlayer } from '../types/fide';
import {
  sanitizeFideGamePayload,
  sanitizeMonthlyRatingPayload,
  sanitizePlayerProfilePayload,
  sanitizeTournamentPayload,
} from './fideValidation';

export function buildSampleFideLedgerDatabase(): FideLedgerDatabase {
  const uid = 'default_player';

  const profile = sanitizePlayerProfilePayload(uid, {
    displayName: 'Roméo Lefèvre',
    fideId: '65104823',
    ffeId: 'K59412',
    federation: 'FRA',
    club: 'Lille Université Club Échecs',
    fideTitle: 'None',
    birthYear: 2003,
    kFactor: 20,
    standardElo: 1868,
    rapidElo: 1905,
    blitzElo: 1932,
    targetElo: 2000,
  });

  const initialOpponents: OpponentPlayer[] = [
    {
      id: 'opp_vandenberghe',
      name: 'Vandenberghe, Lucas',
      fideId: '2049182',
      ffeId: 'B04918',
      elo: 1640,
      standardElo: 1640,
      rapidElo: 1685,
      blitzElo: 1710,
      title: 'None',
      federation: 'BEL',
      club: 'Cercle Royal de Gand',
      notes: 'Joue 1...e5 avec les Noirs (Italienne). Hésite dans les complications tactiques.',
    },
    {
      id: 'opp_moreau',
      name: 'Moreau, Alexandre',
      fideId: '65019284',
      ffeId: 'A50192',
      elo: 2095,
      standardElo: 2095,
      rapidElo: 2140,
      blitzElo: 2180,
      title: 'CM',
      federation: 'FRA',
      club: 'Asnières Le Grand Échiquier',
      notes: 'Candidat Maître très solide en finale. Joue 1.e4 et cherche les petites pressions.',
    },
    {
      id: 'opp_kowalski',
      name: 'Kowalski, Piotr',
      fideId: '1184920',
      ffeId: '',
      elo: 1912,
      standardElo: 1912,
      rapidElo: 1890,
      blitzElo: 1965,
      title: 'None',
      federation: 'POL',
      club: 'Varsovie Chess Club',
      notes: 'Spécialiste de la Sicilienne Najdorf, très théorique sur les 12 premiers coups.',
    },
    {
      id: 'opp_bertrand',
      name: 'Bertrand, Camille',
      fideId: '65198201',
      ffeId: 'H19820',
      elo: 1745,
      standardElo: 1745,
      rapidElo: 1770,
      blitzElo: 1730,
      title: 'None',
      federation: 'FRA',
      club: 'Lyon Olympique Échecs',
      notes: 'Joue le Gambit Dame et le Système de Londres avec les Blancs.',
    },
    {
      id: 'opp_delorme',
      name: 'Delorme, Sébastien',
      fideId: '6089124',
      ffeId: 'F08912',
      elo: 2285,
      standardElo: 2285,
      rapidElo: 2310,
      blitzElo: 2345,
      title: 'FM',
      federation: 'FRA',
      club: 'Échiquier Grenoblois',
      notes: 'Maître FIDE expérimenté. Défense Berlinoise très difficile à percer.',
    },
    {
      id: 'opp_dubois',
      name: 'Dubois, Quentin',
      fideId: '65201943',
      ffeId: 'K20194',
      elo: 1795,
      standardElo: 1795,
      rapidElo: 1830,
      blitzElo: 1860,
      title: 'None',
      federation: 'FRA',
      club: 'Cercle d’Échecs de Béthune',
      notes: 'Adversaire régulier dans le Nord. Joue la Sicilienne et la Caro-Kann.',
    },
  ];

  const monthlyRaw = [
    {
      id: 'fide_2025_11',
      period: '2025-11',
      standardElo: 1764,
      rapidElo: 1810,
      blitzElo: 1840,
      standardGamesCount: 4,
      standardDelta: 8,
      fideRankNational: 4820,
      notes: 'Rentrée Interclubs Nationale 2 (Rondes 1-2)',
    },
    {
      id: 'fide_2025_12',
      period: '2025-12',
      standardElo: 1778,
      rapidElo: 1825,
      blitzElo: 1845,
      standardGamesCount: 5,
      standardDelta: 14,
      fideRankNational: 4690,
      notes: 'Tournoi d’Automne des Hauts-de-France (+14 pts)',
    },
    {
      id: 'fide_2026_01',
      period: '2026-01',
      standardElo: 1772,
      rapidElo: 1830,
      blitzElo: 1860,
      standardGamesCount: 3,
      standardDelta: -6,
      fideRankNational: 4735,
      notes: 'Légère baisse en ronde d’hiver Interclubs',
    },
    {
      id: 'fide_2026_02',
      period: '2026-02',
      standardElo: 1785,
      rapidElo: 1842,
      blitzElo: 1875,
      standardGamesCount: 3,
      standardDelta: 13,
      fideRankNational: 4580,
      notes: 'Victoire contre un 1940 FIDE en Nationale 2',
    },
    {
      id: 'fide_2026_03',
      period: '2026-03',
      standardElo: 1819,
      rapidElo: 1855,
      blitzElo: 1880,
      standardGamesCount: 9,
      standardDelta: 34,
      fideRankNational: 4210,
      notes: 'Publication Open International de Cappelle-la-Grande (+34 pts)',
    },
    {
      id: 'fide_2026_04',
      period: '2026-04',
      standardElo: 1827,
      rapidElo: 1868,
      blitzElo: 1895,
      standardGamesCount: 2,
      standardDelta: 8,
      fideRankNational: 4130,
      notes: 'Week-end de clôture Interclubs N2',
    },
    {
      id: 'fide_2026_05',
      period: '2026-05',
      standardElo: 1822,
      rapidElo: 1880,
      blitzElo: 1910,
      standardGamesCount: 4,
      standardDelta: -5,
      fideRankNational: 4180,
      notes: 'Open FIDE de l’Ascension',
    },
    {
      id: 'fide_2026_06',
      period: '2026-06',
      standardElo: 1831,
      rapidElo: 1890,
      blitzElo: 1915,
      standardGamesCount: 3,
      standardDelta: 9,
      fideRankNational: 4075,
      notes: 'Coupe Loubatière phase interrégionale',
    },
    {
      id: 'fide_2026_07',
      period: '2026-07',
      standardElo: 1831,
      rapidElo: 1895,
      blitzElo: 1920,
      standardGamesCount: 0,
      standardDelta: 0,
      fideRankNational: 4070,
      notes: 'Aucune partie Standard comptabilisée en juin',
    },
    {
      id: 'fide_2026_08',
      period: '2026-08',
      standardElo: 1854,
      rapidElo: 1900,
      blitzElo: 1928,
      standardGamesCount: 9,
      standardDelta: 23,
      fideRankNational: 3820,
      notes: 'Open International d’Été de Lyon (Nulle contre un Maître FIDE)',
    },
    {
      id: 'fide_2026_09',
      period: '2026-09',
      standardElo: 1860,
      rapidElo: 1905,
      blitzElo: 1932,
      standardGamesCount: 2,
      standardDelta: 6,
      fideRankNational: 3765,
      notes: 'Match homologué de rentrée',
    },
    {
      id: 'fide_2026_10',
      period: '2026-10',
      standardElo: 1868,
      rapidElo: 1905,
      blitzElo: 1932,
      standardGamesCount: 3,
      standardDelta: 8,
      fideRankNational: 3690,
      notes: 'Nouveau record personnel Standard FIDE (1868)',
    },
  ];

  const ratingHistory = monthlyRaw.map((rec) => ({
    id: rec.id,
    ...sanitizeMonthlyRatingPayload(uid, rec),
  }));

  const t1Id = 't_cappelle_2026';
  const t2Id = 't_lyon_2026';
  const t3Id = 't_lille_oct2026';

  const tournamentsRaw = [
    {
      id: t1Id,
      name: '42e Open International de Cappelle-la-Grande',
      location: 'Cappelle-la-Grande, FRA',
      startDate: '2026-02-14',
      endDate: '2026-02-20',
      timeControl: 'Standard' as const,
      timeControlDetails: '90 min / 40 coups + 30 min + 30 sec/coup',
      format: 'Swiss' as const,
      totalRounds: 9,
      totalPlayers: 248,
      finalRank: 34,
      startingElo: 1785,
      status: 'completed' as const,
      normTarget: '1er Prix Catégorie < 1900',
      notes: 'Super tournoi (34e sur 248 joueurs). Gain total de +26.6 points Elo FIDE.',
    },
    {
      id: t2Id,
      name: 'Open International FIDE d’Été de Lyon',
      location: 'Lyon, FRA',
      startDate: '2026-07-18',
      endDate: '2026-07-25',
      timeControl: 'Standard' as const,
      timeControlDetails: '90 min + 30 sec/coup dès le 1er coup',
      format: 'Swiss' as const,
      totalRounds: 9,
      totalPlayers: 142,
      finalRank: 19,
      startingElo: 1831,
      status: 'completed' as const,
      normTarget: 'Performance > 1950 FIDE',
      notes: '19e place sur 142 joueurs. Nulle contre un Maître FIDE à 2285.',
    },
    {
      id: t3Id,
      name: 'Festival FIDE d’Automne de Lille 2026',
      location: 'Lille, FRA',
      startDate: '2026-10-03',
      endDate: '2026-10-11',
      timeControl: 'Standard' as const,
      timeControlDetails: '90 min / 40 coups + 30 min + 30 sec/coup',
      format: 'Swiss' as const,
      totalRounds: 7,
      totalPlayers: 96,
      finalRank: 8,
      startingElo: 1868,
      status: 'ongoing' as const,
      normTarget: 'Franchir la barre des 1900 FIDE',
      notes: 'Tournoi d’octobre en cours — les variations Elo compteront pour la liste du 1er novembre.',
    },
  ];

  const tournaments = tournamentsRaw.map((t) => ({
    id: t.id,
    ...sanitizeTournamentPayload(uid, t),
  }));

  const sampleGamesRaw = [
    {
      id: 'g_1',
      tournamentId: t1Id,
      tournamentName: '42e Open International de Cappelle-la-Grande',
      round: 1,
      datePlayed: '2026-02-14',
      timeControl: 'Standard' as const,
      playerColor: 'White' as const,
      playerElo: 1785,
      opponentId: 'opp_vandenberghe',
      opponentName: 'Vandenberghe, Lucas',
      opponentFideId: '2049182',
      opponentFfeId: 'B04918',
      opponentTitle: 'None' as const,
      opponentElo: 1640,
      opponentFederation: 'BEL',
      result: '1-0' as const,
      playerScore: 1 as const,
      eloChange: 6.0,
      kFactorUsed: 20 as const,
      ecoCode: 'C54',
      openingName: 'Partie Italienne, Ligne Principale avec c3 et d4',
      movesCount: 34,
      termination: 'Resignation' as const,
      pgn: '1. e4 e5 2. Nf3 Nc6 3. Bc4 Bc5 4. c3 Nf6 5. d3 d6 6. O-O O-O 7. Re1 a6 8. Bb3 Ba7 9. Nbd2 Ne7 10. Nf1 Ng6 11. Ng3 c6 12. d4 exd4 13. cxd4 Bg4 14. Be3 Nh4 15. Nxh4 Bxd1 16. Raxd1 Nxe4 17. Nxe4 Qxh4 18. Bg5 Qh5 19. Rd3 d5 20. Nf6+ gxf6 21. Bxf6 Rfe8 22. Rg3+ Kf8 23. Bg7+ Kg8 24. Be5+ Kf8 25. Bd6+',
      chessComUrl: 'https://www.chess.com/analysis',
      keyMomentNote: 'Sacrifice positionnel en f6 après l’ouverture de la colonne g pour exploiter le Roi noir.',
    },
    {
      id: 'g_2',
      tournamentId: t1Id,
      tournamentName: '42e Open International de Cappelle-la-Grande',
      round: 2,
      datePlayed: '2026-02-15',
      timeControl: 'Standard' as const,
      playerColor: 'Black' as const,
      playerElo: 1785,
      opponentId: 'opp_moreau',
      opponentName: 'Moreau, Alexandre',
      opponentFideId: '65019284',
      opponentFfeId: 'A50192',
      opponentTitle: 'CM' as const,
      opponentElo: 2095,
      opponentFederation: 'FRA',
      result: '1/2-1/2' as const,
      playerScore: 0.5 as const,
      eloChange: 7.2,
      kFactorUsed: 20 as const,
      ecoCode: 'B18',
      openingName: 'Défense Caro-Kann, Variante Classique',
      movesCount: 48,
      termination: 'Agreement' as const,
      pgn: '1. e4 c6 2. d4 d5 3. Nc3 dxe4 4. Nxe4 Bf5 5. Ng3 Bg6 6. h4 h6 7. Nf3 Nd7 8. h5 Bh7 9. Bd3 Bxd3 10. Qxd3 e6 11. Bf4 Qa5+ 12. Bd2 Bb4 13. c3 Be7 14. c4 Qc7 15. O-O-O Ngf6',
      chessComUrl: 'https://www.chess.com/analysis',
      keyMomentNote: 'Structure Caro-Kann très solide, finale de tours défendue avec précision contre un Candidat Maître.',
    },
    {
      id: 'g_3',
      tournamentId: t1Id,
      tournamentName: '42e Open International de Cappelle-la-Grande',
      round: 3,
      datePlayed: '2026-02-16',
      timeControl: 'Standard' as const,
      playerColor: 'White' as const,
      playerElo: 1785,
      opponentId: 'opp_kowalski',
      opponentName: 'Kowalski, Piotr',
      opponentFideId: '1184920',
      opponentFfeId: '',
      opponentTitle: 'None' as const,
      opponentElo: 1912,
      opponentFederation: 'POL',
      result: '1-0' as const,
      playerScore: 1 as const,
      eloChange: 13.4,
      kFactorUsed: 20 as const,
      ecoCode: 'B90',
      openingName: 'Défense Sicilienne, Variante Najdorf',
      movesCount: 39,
      termination: 'Checkmate' as const,
      pgn: '1. e4 c5 2. Nf3 d6 3. d4 cxd4 4. Nxd4 Nf6 5. Nc3 a6 6. Be3 e5 7. Nb3 Be6 8. f3 Be7 9. Qd2 O-O 10. O-O-O Nbd7 11. g4 b5 12. g5 b4 13. Ne2 Ne8 14. f4 a5 15. f5 Bxb3 16. cxb3',
      chessComUrl: 'https://www.chess.com/analysis',
      keyMomentNote: 'Attaque anglaise contre la Najdorf : percée f4-f5 décisive.',
    },
    {
      id: 'g_4',
      tournamentId: t2Id,
      tournamentName: 'Open International FIDE d’Été de Lyon',
      round: 1,
      datePlayed: '2026-07-18',
      timeControl: 'Standard' as const,
      playerColor: 'Black' as const,
      playerElo: 1831,
      opponentId: 'opp_bertrand',
      opponentName: 'Bertrand, Camille',
      opponentFideId: '65198201',
      opponentFfeId: 'H19820',
      opponentTitle: 'None' as const,
      opponentElo: 1745,
      opponentFederation: 'FRA',
      result: '0-1' as const,
      playerScore: 1 as const,
      eloChange: 7.6,
      kFactorUsed: 20 as const,
      ecoCode: 'D37',
      openingName: 'Gambit Dame Refusé, Variante des Trois Cavaliers',
      movesCount: 41,
      termination: 'Resignation' as const,
      pgn: '1. d4 d5 2. c4 e6 3. Nc3 Nf6 4. Nf3 Be7 5. Bf4 O-O 6. e3 c5 7. dxc5 Bxc5 8. a3 Nc6 9. Qc2 Qa5 10. Rd1 Be7 11. Nd2 e5 12. Bg5 d4',
      chessComUrl: 'https://www.chess.com/analysis',
      keyMomentNote: 'Libération centrale thématique ...c5 puis ...d4.',
    },
    {
      id: 'g_5',
      tournamentId: t2Id,
      tournamentName: 'Open International FIDE d’Été de Lyon',
      round: 4,
      datePlayed: '2026-07-21',
      timeControl: 'Standard' as const,
      playerColor: 'White' as const,
      playerElo: 1831,
      opponentId: 'opp_delorme',
      opponentName: 'Delorme, Sébastien',
      opponentFideId: '6089124',
      opponentFfeId: 'F08912',
      opponentTitle: 'FM' as const,
      opponentElo: 2285,
      opponentFederation: 'FRA',
      result: '1/2-1/2' as const,
      playerScore: 0.5 as const,
      eloChange: 8.4,
      kFactorUsed: 20 as const,
      ecoCode: 'C65',
      openingName: 'Partie Espagnole (Ruy Lopez), Défense Berlinoise',
      movesCount: 54,
      termination: 'Threefold Repetition' as const,
      pgn: '1. e4 e5 2. Nf3 Nc6 3. Bb5 Nf6 4. d3 Bc5 5. c3 O-O 6. O-O d6 7. Nbd2 a6 8. Ba4 Ba7 9. Re1 Ne7 10. Nf1 Ng6 11. Ng3 h6 12. h3 Be6',
      chessComUrl: 'https://www.chess.com/analysis',
      keyMomentNote: 'Première nulle homologuée contre un Maître FIDE (>2280).',
    },
    {
      id: 'g_6',
      tournamentId: t3Id,
      tournamentName: 'Festival FIDE d’Automne de Lille 2026',
      round: 1,
      datePlayed: '2026-10-03',
      timeControl: 'Standard' as const,
      playerColor: 'White' as const,
      playerElo: 1868,
      opponentId: 'opp_dubois',
      opponentName: 'Dubois, Quentin',
      opponentFideId: '65201943',
      opponentFfeId: 'K20194',
      opponentTitle: 'None' as const,
      opponentElo: 1790,
      opponentFederation: 'FRA',
      result: '1-0' as const,
      playerScore: 1 as const,
      eloChange: 7.8,
      kFactorUsed: 20 as const,
      ecoCode: 'B22',
      openingName: 'Défense Sicilienne, Variante Alapin (c3)',
      movesCount: 31,
      termination: 'Resignation' as const,
      pgn: '1. e4 c5 2. c3 Nf6 3. e5 Nd5 4. d4 cxd4 5. Nf3 Nc6 6. cxd4 d6 7. Bc4 Nb6 8. Bb5 dxe5 9. Nxe5 Bd7 10. Nxd7 Qxd7 11. Nc3 e6 12. O-O Be7 13. Qg4 O-O 14. Bxc6 Qxc6 15. Bh6 Bf6 16. Ne4',
      chessComUrl: 'https://www.chess.com/analysis',
      keyMomentNote: 'Attaque directe sur l’aile roi avec 13.Qg4 et 15.Bh6.',
    },
    {
      id: 'g_7',
      tournamentId: t3Id,
      tournamentName: 'Festival FIDE d’Automne de Lille 2026',
      round: 2,
      datePlayed: '2026-10-04',
      timeControl: 'Standard' as const,
      playerColor: 'Black' as const,
      playerElo: 1868,
      opponentId: 'opp_dubois',
      opponentName: 'Dubois, Quentin',
      opponentFideId: '65201943',
      opponentFfeId: 'K20194',
      opponentTitle: 'None' as const,
      opponentElo: 1795,
      opponentFederation: 'FRA',
      result: '0-1' as const,
      playerScore: 1 as const,
      eloChange: 7.9,
      kFactorUsed: 20 as const,
      ecoCode: 'B12',
      openingName: 'Défense Caro-Kann, Variante d’Avance',
      movesCount: 40,
      termination: 'Resignation' as const,
      pgn: '1. e4 c6 2. d4 d5 3. e5 Bf5 4. Nf3 e6 5. Be2 Nd7 6. O-O Ne7',
      chessComUrl: 'https://www.chess.com/analysis',
      keyMomentNote: 'Deuxième victoire contre Quentin Dubois cette saison.',
    },
  ];

  const games = sampleGamesRaw.map((g) => ({
    id: g.id,
    ...sanitizeFideGamePayload(uid, g),
  }));

  const opponents = syncOpponentsWithGames(initialOpponents, games);

  return {
    version: 1,
    updatedAt: new Date().toISOString(),
    profile,
    opponents,
    tournaments,
    games,
    ratingHistory,
  };
}
